lista_juegos = [
    {
        "nombre": "Counter-Strike 2",
        "edad": 18,
        "genero": "accion",
        "modo_juego": "multijugador",
        "cant_amigos": 9,
        "perfil_jugador": "competitivo",
        "plataforma": "pc",
        "gama": 1,
        "espacio_disco": 85,
        "duracion": "corto",
        "valor": 0,
        "puntos": 0,
#        "frecuencia_recomendacion" : 0
    },
{
        "nombre": "Fortnite",
        "edad": 13,
        "genero": "accion",
        "modo_juego": "multijugador",
        "cant_amigos": 15,
        "perfil_jugador": "competitivo",
        "plataforma": "consola",
        "gama": 2,
        "espacio_disco": 79,
        "duracion": "corto",
        "valor": 0,
        "puntos": 0,
#        "frecuencia_recomendacion" : 0
    },
{
        "nombre": "Skyrim",
        "edad": 18,
        "genero": "accion",
        "modo_juego": "solo",
        "cant_amigos": 0,
        "perfil_jugador": "casual",
        "plataforma": "consola",
        "gama": 1,
        "espacio_disco": 12,
        "duracion": "largo",
        "valor": 23.99,
        "puntos": 0,
#        "frecuencia_recomendacion" : 0
    },
{
        "nombre": "God of War: Ragnarok",
        "edad": 18,
        "genero": "historia",
        "modo_juego": "solo",
        "cant_amigos": 0,
        "perfil_jugador": "casual",
        "plataforma": "consola",
        "gama": 3,
        "espacio_disco": 70,
        "duracion": "largo",
        "valor": 49.99,
        "puntos": 0,
#        "frecuencia_recomendacion" : 0
    },
{
        "nombre": "Uncharted: Coleccion de Legado",
        "edad": 13,
        "genero": "historia",
        "modo_juego": "solo",
        "cant_amigos": 0,
        "perfil_jugador": "casual",
        "plataforma": "consola",
        "gama": 2,
        "espacio_disco": 126,
        "duracion": "largo",
        "valor": 49.99,
        "puntos": 0,
#        "frecuencia_recomendacion" : 0
    },
{
        "nombre": "Dragon Age",
        "edad": 18,
        "genero": "historia",
        "modo_juego": "multijugador",
        "cant_amigos": 3,
        "perfil_jugador": "casual",
        "plataforma": "consola",
        "gama": 1,
        "espacio_disco": 100,
        "duracion": "largo",
        "valor": 29.99,
        "puntos": 0,
#        "frecuencia_recomendacion" : 0
    },
{
        "nombre": "League Of Legends",
        "edad": 0,
        "genero": "estrategia",
        "modo_juego": "multijugador",
        "cant_amigos": 9,
        "perfil_jugador": "competitivo",
        "plataforma": "pc",
        "gama": 1,
        "espacio_disco": 37,
        "duracion": "corto",
        "valor": 0,
        "puntos": 0,
#       "frecuencia_recomendacion" : 0
    },
{
        "nombre": "Age Of Empires",
        "edad": 13,
        "genero": "estrategia",
        "modo_juego": "solo",
        "cant_amigos": 3,
        "perfil_jugador": "competitivo",
        "plataforma": "consola",
        "gama": 1,
        "espacio_disco": 50,
        "duracion": "corto",
        "valor": 19.99,
        "puntos": 0,
#        "frecuencia_recomendacion" : 0
    },
{
        "nombre": "X-Com",
        "edad": 14,
        "genero": "estrategia",
        "modo_juego": "solo",
        "cant_amigos": 0,
        "perfil_jugador": "casual",
        "plataforma": "consola",
        "gama": 1,
        "espacio_disco": 45,
        "duracion": "corto",
        "valor": 19.99,
        "puntos": 0,
#        "frecuencia_recomendacion" : 0
    },
{
        "nombre": "Overcooked II",
        "edad": 0,
        "genero": "accion",
        "modo_juego": "cooperativo",
        "cant_amigos": 3,
        "perfil_jugador": "casual",
        "plataforma": "consola",
        "gama": 1,
        "espacio_disco": 3,
        "duracion": "corto",
        "valor": 12.49,
        "puntos": 0,
#        "frecuencia_recomendacion" : 0
    }
]